import type { Metadata } from "next/types";
import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "../public/logo.svg?url";
import Image from "next/image";
import Button from "./component/Button";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased min-h-screen w-full`}>
        <div className="min-h-screen w-full flex flex-col">
          {/* 고정 헤더 */}
          <header className="sticky top-0 z-50 h-16 w-full flex justify-center items-center bg-[#F5F5F4]">
            <div className="container mx-auto flex items-center gap-6 justify-between">
              <div className="flex items-center gap-6">
                <Image src={Logo} alt="logo" width={66} height={32} />
                <Link href="/introduction">Introduction</Link>
                <span className="cursor-pointer">Pricing</span>
                <span className="cursor-pointer">Management</span>
              </div>
              <div className="flex items-center gap-2">
                <Button variant="outlined">Contact Sales</Button>
                <Button variant="contained">Sign In</Button>
              </div>
            </div>
          </header>

          {/* 메인 콘텐츠 영역 - 스크롤 가능 */}
          <main className="flex-1 w-full flex justify-center">
            <div className="w-full">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
